name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild build -workspace Events.xcworkspace -scheme Events -destination 'generic/platform=iOS' | xcpretty
    - name: Run tests
      run: xcodebuild test -workspace Events.xcworkspace -scheme Events -destination 'platform=iOS Simulator,name=iPhone SE,OS=12.4' | xcpretty -s
