name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle Install
      run: bundle install
    - name: pod install
      run: bundle exec pod install || bundle exec pod install --repo-update
    - name: Build
      run: xcodebuild build -workspace Events.xcworkspace -scheme Events -destination 'generic/platform=iOS' | xcpretty -allowProvisioningUpdates
    - name: Run tests
      run: xcodebuild test -workspace Events.xcworkspace -scheme Events -destination 'platform=iOS Simulator,name=iPhone SE (2nd generation),OS=14.4' | xcpretty -s
